# Generated by Django 4.2.7 on 2025-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('reg_no', models.CharField(db_column='Reg No', max_length=20)),
                ('program_title', models.CharField(db_column='Program Title', max_length=200)),
                ('date', models.DateField(db_column='Date')),
                ('services_required', models.TextField(db_column='Services Required')),
                ('auditorium_name', models.CharField(db_column='Auditorium Name', max_length=100)),
                ('requestor_detail', models.TextField(db_column='Requestor Detail')),
            ],
            options={
                'db_table': 'one',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('sl', models.IntegerField(db_column='Sl.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('collection', models.CharField(max_length=255)),
                ('ebook_isbn', models.CharField(db_column='ebook ISBN', max_length=20)),
                ('doi', models.CharField(db_column='DOI', max_length=100)),
                ('url', models.URLField(db_column='URL', max_length=255)),
                ('subject_category', models.CharField(db_column='Subject Category', max_length=255)),
                ('book_type', models.CharField(db_column='Book Type', max_length=50)),
            ],
            options={
                'db_table': 'two',
                'managed': False,
            },
        ),
    ]
