# Generated by Django 4.2.7 on 2025-05-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ebook',
            table='three',
        ),
    ]
